//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Agendo.UI.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Agendo.UI.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cod. Sucursal.
        /// </summary>
        public static string ClienteModel_CodSucursal {
            get {
                return ResourceManager.GetString("ClienteModel_CodSucursal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alias.
        /// </summary>
        public static string ClienteModel_List_Alias {
            get {
                return ResourceManager.GetString("ClienteModel_List_Alias", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to F. Pago.
        /// </summary>
        public static string ClienteModel_List_FPago {
            get {
                return ResourceManager.GetString("ClienteModel_List_FPago", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saldo.
        /// </summary>
        public static string ClienteModel_List_Saldo {
            get {
                return ResourceManager.GetString("ClienteModel_List_Saldo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Z. Reparto.
        /// </summary>
        public static string ClienteModel_List_ZReparto {
            get {
                return ResourceManager.GetString("ClienteModel_List_ZReparto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Memotecnico.
        /// </summary>
        public static string ClienteModel_Memotecnico {
            get {
                return ResourceManager.GetString("ClienteModel_Memotecnico", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nombre de Fantasia.
        /// </summary>
        public static string ClienteModel_NombreFantasia {
            get {
                return ResourceManager.GetString("ClienteModel_NombreFantasia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Observación.
        /// </summary>
        public static string ClienteModel_Observacion {
            get {
                return ResourceManager.GetString("ClienteModel_Observacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saldo Max..
        /// </summary>
        public static string ClienteModel_SaldoMax {
            get {
                return ResourceManager.GetString("ClienteModel_SaldoMax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Estado.
        /// </summary>
        public static string ClientModel_Estado {
            get {
                return ResourceManager.GetString("ClientModel_Estado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forma de Pago.
        /// </summary>
        public static string ClientModel_FormaPago {
            get {
                return ResourceManager.GetString("ClientModel_FormaPago", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giro.
        /// </summary>
        public static string ClientModel_Giro {
            get {
                return ResourceManager.GetString("ClientModel_Giro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zona de Reparto.
        /// </summary>
        public static string ClientModel_ZonaReparto {
            get {
                return ResourceManager.GetString("ClientModel_ZonaReparto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ya existe en el sistema.
        /// </summary>
        public static string ClientRut_Duplicate_Error {
            get {
                return ResourceManager.GetString("ClientRut_Duplicate_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comuna.
        /// </summary>
        public static string DireccionModel_Comuna {
            get {
                return ResourceManager.GetString("DireccionModel_Comuna", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calle .
        /// </summary>
        public static string DireccionModel_Descripcion {
            get {
                return ResourceManager.GetString("DireccionModel_Descripcion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Número.
        /// </summary>
        public static string DireccionModel_Numero {
            get {
                return ResourceManager.GetString("DireccionModel_Numero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provincia.
        /// </summary>
        public static string DireccionModel_Provincia {
            get {
                return ResourceManager.GetString("DireccionModel_Provincia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Región.
        /// </summary>
        public static string DireccionModel_Region {
            get {
                return ResourceManager.GetString("DireccionModel_Region", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipo.
        /// </summary>
        public static string DireccionModel_Tipo {
            get {
                return ResourceManager.GetString("DireccionModel_Tipo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string EntidadModel_Email {
            get {
                return ResourceManager.GetString("EntidadModel_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nombre.
        /// </summary>
        public static string EntidadModel_Nombre {
            get {
                return ResourceManager.GetString("EntidadModel_Nombre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RUT Invalido.
        /// </summary>
        public static string EntidadModel_Rut_InvalidFormat {
            get {
                return ResourceManager.GetString("EntidadModel_Rut_InvalidFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string LoginModel_Password {
            get {
                return ResourceManager.GetString("LoginModel_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuario.
        /// </summary>
        public static string LoginModel_UserName {
            get {
                return ResourceManager.GetString("LoginModel_UserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipo.
        /// </summary>
        public static string Tipo {
            get {
                return ResourceManager.GetString("Tipo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} es requerido.
        /// </summary>
        public static string View_Required {
            get {
                return ResourceManager.GetString("View_Required", resourceCulture);
            }
        }
    }
}
